### ISSUE TITLE
error on getting data sets

### ISSUE THREAD

**Issue by PurushothamVatuvugunta** [MSamyal/coursera_capstone_2020#1]
where u get this file covid_data_nyc.csv , can u help mee

**Comment by MSamyal** [comment]
[data:application/octet-stream;charset=utf-8,ZIP%2CNeighborhood%2CTotal%20cases%20(4%20weeks)%2CCOVID_CASE_RATE_WEEK4%2CCOVID_CASE_RATE_WEEK3%2CCOVID_CASE_RATE_WEEK2%2CCOVID_CASE_RATE_WEEK1%2C2-week%20change%0A10001%2CChelsea%2FNoMad%2FWest%20Chelsea%2C15%2C16.98%2C12.73%2C25.46%2C8.49%2C14%0A10002%2CChinatown%2FLower%20East%20Side%2C58%2C31.27%2C10.42%2C22.15%2C11.73%2C-19%0A10003%2CEast%20Village%2FGramercy%2FGreenwich%20Village%2C25%2C7.43%2C3.72%2C18.59%2C16.73%2C217%0A10004%2CFinancial%20District%2C1%2C0%2C0%2C27.39%2C0%2Cnull%0A10005%2CFinancial%20District%2C11%2C35.73%2C47.64%2C23.82%2C23.82%2C-43%0A10006%2CFinancial%20District%2C2%2C0%2C0%2C0%2C57.84%2Cnull%0A10007%2CTriBeCa%2C3%2C12.12%2C12.12%2C0%2C12.12%2C-50%0A10009%2CAlphabet%20City%2FEast%20Village%2FStuyvesant%20Town-Cooper%20Village%2C28%2C15.32%2C6.81%2C17.02%2C8.51%2C15%0A10010%2CFlatiron%2FGramercy%2FKips%20Bay%2C29%2C27.8%2C24.71%2C12.36%2C24.71%2C-29%0A10011%2CChelsea%2C26%2C6.06%2C10.1%2C24.24%2C12.12%2C125%0A10012%2CGreenwich%20Village%2FSoHo%2C19%2C20.85%2C25.02%2C16.68%2C16.68%2C-27%0A10013%2CHudson%20Square%2FLittle%20Italy%2FSoHo%2FTriBeCa%2C15%2C17.22%2C20.67%2C6.89%2C6.89%2C-64%0A10014%2CHudson%20Square%2FMeatpacking%20District%2FWest%20Village%2C12%2C6.44%2C6.44%2C12.89%2C12.89%2C100%0A10016%2CKips%20Bay%2FMurray%20Hill%2FNoMad%2C42%2C11.42%2C19.04%2C26.65%2C22.85%2C63%0A10017%2CEast%20Midtown%2FMurray%20Hill%2C4%2C6.2%2C0%2C12.4%2C6.2%2C200%0A10018%2CHell's%20Kitchen%2FMidtown%20Manhattan%2C10%2C41.97%2C10.49%2C41.97%2C10.49%2C0%0A10019%2CHell's%20Kitchen%2FMidtown%20Manhattan%2C27%2C22.15%2C14.77%2C14.77%2C14.77%2C-20%0A10021%2CLenox%20Hill%2FUpper%20East%20Side%2C19%2C9.05%2C9.05%2C11.32%2C13.58%2C38%0A10022%2CEast%20Midtown%2C17%2C16.48%2C6.59%2C16.48%2C16.48%2C43%0A10023%2CLincoln%20Square%2C24%2C14.93%2C13.27%2C8.3%2C3.32%2C-59%0A10024%2CUpper%20West%20Side%2C27%2C12.21%2C20.93%2C5.23%2C8.72%2C-58%0A10025%2CManhattan%20Valley%2FMorningside%20Heights%2FUpper%20West%20Side%2C51%2C8.66%2C10.83%2C16.25%2C19.49%2C83%0A10026%2CCentral%20Harlem%20(South)%2C33%2C7.69%2C25.63%2C30.76%2C20.5%2C54%0A10027%2CCentral%20Harlem%20(South)%2FMorningside%20Heights%2FWest%20Harlem%2C31%2C12.57%2C6.29%2C15.72%2C14.14%2C58%0A10028%2CUpper%20East%20Side%2FYorkville%2C26%2C14.24%2C10.17%2C18.31%2C10.17%2C17%0A10029%2CEast%20Harlem%2C75%2C27.9%2C20.29%2C22.83%2C24.1%2C-3%0A10030%2CCentral%20Harlem%20(North)%2C18%2C23.87%2C6.82%2C10.23%2C20.46%2C0%0A10031%2CHamilton%20Heights%2FWest%20Harlem%2C51%2C14.86%2C23.12%2C19.82%2C26.42%2C22%0A10032%2CWashington%20Heights%20(South)%2C74%2C39.03%2C30.9%2C24.39%2C26.02%2C-28%0A10033%2CWashington%20Heights%20(North)%2FWashington%20Heights%20(South)%2C60%2C23.64%2C35.47%2C20.27%2C21.96%2C-29%0A10034%2CInwood%2FWashington%20Heights%20(North)%2C50%2C32.5%2C25.54%2C34.82%2C23.22%2C0%0A10035%2CEast%20Harlem%2C22%2C17.43%2C8.71%2C26.14%2C11.62%2C44%0A10036%2CHell's%20Kitchen%2FMidtown%20Manhattan%2C16%2C3.82%2C22.89%2C19.08%2C15.26%2C29%0A10037%2CCentral%20Harlem%20(North)%2FEast%20Harlem%2C22%2C19.37%2C29.06%2C33.9%2C24.21%2C20%0A10038%2CChinatown%2FFinancial%20District%2C20%2C9.07%2C18.14%2C13.61%2C49.89%2C133%0A10039%2CCentral%20Harlem%20(North)%2FWashington%20Heights%20(South)%2C31%2C30.24%2C41.58%2C34.02%2C11.34%2C-37%0A10040%2CWashington%20Heights%20(North)%2C53%2C31.24%2C26.78%2C26.78%2C33.48%2C4%0A10044%2CRoosevelt%20Island%2C4%2C0%2C17.09%2C0%2C17.09%2C0%0A10065%2CLenox%20Hill%2FUpper%20East%20Side%2C13%2C10.32%2C6.88%2C20.65%2C6.88%2C60%0A10069%2CLincoln%20Square%2C6%2C31.56%2C0%2C31.56%2C31.56%2C100%0A10075%2CLenox%20Hill%2FUpper%20East%20Side%2C12%2C21.16%2C16.92%2C4.23%2C8.46%2C-67%0A10128%2CUpper%20East%20Side%2FYorkville%2C14%2C4.89%2C4.89%2C4.89%2C8.15%2C33%0A10280%2CBattery%20Park%20City%2C1%2C10.4%2C0%2C0%2C0%2C-100%0A10282%2CBattery%20Park%20City%2C2%2C18.13%2C0%2C18.13%2C0%2C0%0A10301%2CSilver%20Lake%2FSt.%20George%2C34%2C22.72%2C20.2%2C15.15%2C27.77%2C0%0A10302%2CElm%20Park%2C14%2C21.31%2C21.31%2C10.65%2C21.31%2C-25%0A10303%2CGraniteville%2FMariner's%20Harbor%2FPort%20Ivory%2C19%2C22.87%2C26.69%2C7.62%2C15.25%2C-54%0A10304%2CNew%20Dorp%2FTodt%20Hill%2C45%2C16.49%2C30.63%2C42.4%2C16.49%2C25%0A10305%2CArrochar%2FMidland%20Beach%2FShore%20Acres%2FSouth%20Beach%20Ocean%20Breeze%2C32%2C11.75%2C28.19%2C16.45%2C18.8%2C-12%0A10306%2CLighthouse%20Hill%2FMidland%20Beach%2FNew%20Dorp%2FOakwood%2C34%2C16.76%2C14.9%2C16.76%2C14.9%2C0%0A10307%2CTottenville%2C6%2C13.15%2C6.57%2C13.15%2C6.57%2C0%0A10308%2CGreat%20Kills%2C20%2C6.75%2C10.12%2C40.49%2C10.12%2C200%0A10309%2CCharleston%2FPrince's%20Bay%2FWoodrow%2C14%2C12.12%2C15.15%2C6.06%2C9.09%2C-44%0A10310%2CPort%20Richmond%2FRandall%20Manor%2FWest%20Brighton%2C19%2C8.38%2C29.32%2C12.57%2C29.32%2C11%0A10312%2CAnnadale%2FRossville%2C38%2C14.92%2C18.24%2C8.29%2C21.56%2C-10%0A10314%2CBloomfield%2FFreshkills%20Park%2C75%2C13.21%2C25.32%2C25.32%2C18.72%2C14%0A10451%2CConcourse%2FMelrose%2C60%2C44.01%2C23.05%2C46.1%2C12.57%2C-13%0A10452%2CConcourse%2FHighbridge%2C122%2C41.54%2C40.24%2C40.24%2C36.35%2C-6%0A10453%2CMorris%20Heights%2FMount%20Hope%2FUniversity%20Heights%2C118%2C30.79%2C40.65%2C38.18%2C35.72%2C3%0A10454%2CMott%20Haven%2FPort%20Morris%2C37%2C20.93%2C39.24%2C18.31%2C18.31%2C-39%0A10455%2CMott%20Haven%2C59%2C30.82%2C35.57%2C42.68%2C30.82%2C11%0A10456%2CClaremont%2FMorrisania%2C89%2C28.89%2C25.68%2C21.4%2C19.26%2C-25%0A10457%2CBelmont%2FClaremont%2FMount%20Hope%2FTremont%2C71%2C18.75%2C20.08%2C28.12%2C28.12%2C45%0A10458%2CBelmont%2FFordham%20University%2FKingsbridge%2C99%2C39.38%2C28.64%2C23.86%2C26.25%2C-26%0A10459%2CCharlotte%20Gardens%2FHunts%20Point%2C48%2C24.82%2C10.34%2C31.02%2C33.09%2C82%0A10460%2CCharlotte%20Gardens%2FTremont%2FVan%20Nest%2FWest%20Farms%2C72%2C38.29%2C38.29%2C19.98%2C23.3%2C-43%0A10461%2CMorris%20Park%2FPelham%20Bay%2FWestchester%20Square%2C38%2C20.21%2C10.11%2C16.17%2C30.32%2C53%0A10462%2CParkchester%2FPelham%20Parkway%2FVan%20Nest%2FWestchester%20Square%2C100%2C28.45%2C32.33%2C36.21%2C32.33%2C13%0A10463%2CKingsbridge%2FMarble%20Hill%2FRiverdale%2FSpuyten%20Duyvil%2C64%2C22.44%2C21.04%2C19.64%2C26.65%2C6%0A10464%2CCity%20Island%2C3%2C45.94%2C22.97%2C0%2C0%2C-100%0A10465%2CCountry%20Club%2FThrogs%20Neck%2C28%2C13.94%2C11.62%2C16.27%2C23.24%2C55%0A10466%2CEdenwald%2FWakefield%2C59%2C20.79%2C23.56%2C20.79%2C16.63%2C-16%0A10467%2CAllerton%2FNorwood%2FPelham%20Parkway%2FWilliamsbridge%2C95%2C34.73%2C22.82%2C14.88%2C21.83%2C-36%0A10468%2CFordham%2FKingsbridge%2FUniversity%20Heights%2C101%2C36.51%2C35.21%2C20.87%2C39.12%2C-16%0A10469%2CAllerton%2FBaychester%2FPelham%20Gardens%2FWilliamsbridge%2C51%2C11.19%2C26.57%2C19.58%2C13.98%2C-11%0A10470%2CWakefield%2FWoodlawn%2C15%2C14.18%2C21.27%2C35.45%2C35.45%2C100%0A10471%2CFieldston%2FNorth%20Riverdale%2FRiverdale%2C19%2C32.95%2C18.83%2C9.41%2C28.24%2C-27%0A10472%2CSoundview%2C58%2C17.67%2C22.09%2C20.61%2C25.03%2C15%0A10473%2CCastle%20Hill%2FClason%20Point%2FSoundview%2C58%2C27.45%2C25.84%2C19.38%2C20.99%2C-24%0A10474%2CHunts%20Point%2C7%2C16.08%2C16.08%2C16.08%2C8.04%2C-25%0A10475%2CCo-op%20City%2FEdenwald%2C34%2C34.29%2C18.29%2C13.72%2C11.43%2C-52%0A11004%2CBellerose%2FDouglaston-Little%20Neck%2C9%2C21.32%2C26.65%2C0%2C0%2C-100%0A11101%2CAstoria%20(South)%2FLong%20Island%20City%2FSunnyside%2C35%2C11.36%2C28.41%2C25.57%2C34.09%2C50%0A11102%2CAstoria%20(North)%2C26%2C21.45%2C18.39%2C24.52%2C15.32%2C0%0A11103%2CAstoria%20(North)%2FAstoria%20(South)%2C30%2C19.13%2C21.87%2C27.33%2C13.67%2C0%0A11104%2CSunnyside%2C17%2C20.18%2C20.18%2C12.11%2C16.14%2C-30%0A11105%2CDitmars%20Steinway%2C25%2C11.14%2C13.93%2C22.29%2C22.29%2C78%0A11106%2CAstoria%20(South)%2C29%2C33.62%2C23.28%2C12.93%2C5.17%2C-68%0A11109%2CLong%20Island%20City%2C3%2C19.72%2C0%2C39.44%2C0%2C100%0A11201%2CBrooklyn%20Heights%2FDUMBO%2FDowntown%20Brooklyn%2C38%2C16.42%2C6.57%2C14.78%2C24.63%2C71%0A11203%2CEast%20Flatbush%20(North)%2FEast%20Flatbush%20(South)%2C35%2C9.54%2C5.45%2C8.18%2C24.53%2C118%0A11204%2CBensonhurst%2FMapleton%2C105%2C25.21%2C42.86%2C32.78%2C31.52%2C-6%0A11205%2CBedford-Stuyvesant%20(West)%2FClinton%20Hill%2FFort%20Greene%2C35%2C18.18%2C20.45%2C9.09%2C31.81%2C6%0A11206%2CWilliamsburg%20(South)%2C52%2C12.87%2C23.39%2C10.53%2C14.04%2C-32%0A11207%2CCypress%20Hills%2FEast%20New%20York%2C47%2C17.95%2C14.58%2C7.85%2C12.34%2C-38%0A11208%2CCypress%20Hills%2FEast%20New%20York%2C82%2C20.92%2C28.24%2C15.69%2C20.92%2C-26%0A11209%2CBay%20Ridge%2FFort%20Hamilton%2C70%2C23.85%2C22.36%2C29.81%2C28.32%2C26%0A11210%2CFlatlands%2FMidwood%2C63%2C11.92%2C22.36%2C31.3%2C28.32%2C74%0A11211%2CEast%20Williamsburg%2FWilliamsburg%20(North)%2FWilliamsburg%20(South)%2C64%2C25.1%2C5.02%2C16.07%2C18.07%2C13%0A11212%2COcean%20Hill-Brownsville%2C41%2C13.82%2C16.33%2C6.28%2C15.08%2C-29%0A11213%2CCrown%20Heights%20(East)%2C41%2C12.42%2C18.63%2C13.97%2C18.63%2C5%0A11214%2CBath%20Beach%2FBensonhurst%2FGravesend%2C69%2C20.36%2C23.57%2C15%2C15%2C-32%0A11215%2CGowanus%2FPark%20Slope%2FWindsor%20Terrace%2C28%2C14.3%2C7.15%2C7.15%2C11.44%2C-13%0A11216%2CBedford-Stuyvesant%20(West)%2FCrown%20Heights%20(West)%2C28%2C12.6%2C12.6%2C7.2%2C18.01%2C0%0A11217%2CBoerum%20Hill%2FPark%20Slope%2C25%2C10.53%2C18.96%2C10.53%2C12.64%2C-21%0A11218%2CKensington%2FWindsor%20Terrace%2C51%2C18.47%2C6.6%2C21.11%2C21.11%2C68%0A11219%2CBorough%20Park%2C98%2C17.23%2C20.46%2C33.38%2C34.46%2C80%0A11220%2CSunset%20Park%2C158%2C39.61%2C72.12%2C19.3%2C29.46%2C-56%0A11221%2CBedford-Stuyvesant%20(East)%2FBushwick%2C54%2C18.37%2C22.04%2C8.57%2C17.14%2C-36%0A11222%2CGreenpoint%2C23%2C19.26%2C22.01%2C8.25%2C13.76%2C-47%0A11223%2CGravesend%2FHomecrest%2C60%2C18.76%2C26.26%2C20.01%2C10.01%2C-33%0A11224%2CBrighton%20Beach%2FConey%20Island%2FSeagate%2C29%2C13.49%2C20.23%2C8.99%2C22.48%2C-7%0A11225%2CCrown%20Heights%20(West)%2FProspect%20Lefferts%20Gardens%2C36%2C10.4%2C22.53%2C12.13%2C17.33%2C-11%0A11226%2CFlatbush%2FProspect%20Lefferts%20Gardens%2C53%2C11.1%2C10.09%2C17.16%2C15.14%2C52%0A11228%2CBath%20Beach%2FDyker%20Heights%2C34%2C22.62%2C20.36%2C18.09%2C15.83%2C-21%0A11229%2CGerritsen%20Beach%2FHomecrest%2FSheepshead%20Bay%2C64%2C18.84%2C17.67%2C14.13%2C24.73%2C6%0A11230%2CMidwood%2C92%2C16.82%2C12.34%2C29.16%2C44.86%2C154%0A11231%2CCarroll%20Gardens%2FCobble%20Hill%2FRed%20Hook%2C17%2C10.81%2C21.62%2C2.7%2C10.81%2C-58%0A11232%2CSunset%20Park%2C34%2C60.13%2C35.37%2C17.69%2C7.07%2C-74%0A11233%2CBedford-Stuyvesant%20(East)%2FOcean%20Hill-Brownsville%2C35%2C15.25%2C12.47%2C12.47%2C8.32%2C-25%0A11234%2CBergen%20Beach%2FFlatlands%2FMarine%20Park%2FMill%20Basin%2C71%2C23.08%2C13.64%2C16.79%2C20.99%2C3%0A11235%2CBrighton%20Beach%2FManhattan%20Beach%2FSheepshead%20Bay%2C94%2C36.46%2C31.43%2C28.92%2C21.37%2C-26%0A11236%2CCanarsie%2C51%2C15.49%2C14.46%2C12.39%2C10.33%2C-24%0A11237%2CBushwick%2FEast%20Williamsburg%2C42%2C33.53%2C23.67%2C15.78%2C9.86%2C-55%0A11238%2CClinton%20Hill%2FProspect%20Heights%2C29%2C12.96%2C12.96%2C12.96%2C14.81%2C7%0A11239%2CEast%20New%20York%2C18%2C64.45%2C16.11%2C16.11%2C48.33%2C-20%0A11354%2CFlushing%2FMurray%20Hill%2C38%2C23.42%2C16.21%2C12.61%2C16.21%2C-27%0A11355%2CFlushing%2FMurray%20Hill%2FQueensboro%20Hill%2C45%2C13.75%2C10%2C21.25%2C11.25%2C37%0A11356%2CCollege%20Point%2C21%2C38.59%2C25.73%2C8.58%2C17.15%2C-60%0A11357%2CWhitestone%2C35%2C15.01%2C30.02%2C27.52%2C15.01%2C-6%0A11358%2CAuburndale%2FMurray%20Hill%2C11%2C11.25%2C8.44%2C2.81%2C8.44%2C-43%0A11360%2CBayside%20(North)%2C11%2C10.6%2C0%2C10.6%2C37.11%2C350%0A11361%2CBayside%20(North)%2FBayside%20(South)%2C14%2C3.58%2C21.45%2C14.3%2C10.73%2C0%0A11362%2CDouglaston-Little%20Neck%2C9%2C28.19%2C5.64%2C11.28%2C5.64%2C-50%0A11363%2CDouglaston-Little%20Neck%2C4%2C27.94%2C13.97%2C13.97%2C0%2C-67%0A11364%2CBayside%20(South)%2FOakland%20Gardens%2C20%2C28.93%2C11.57%2C8.68%2C8.68%2C-57%0A11365%2CAuburndale%2FFresh%20Meadows%2FPomonok%2FUtopia%2C27%2C13.62%2C22.7%2C13.62%2C11.35%2C-31%0A11366%2CFresh%20Meadows%2FHillcrest%2C11%2C29.03%2C0%2C36.29%2C14.52%2C75%0A11367%2CKew%20Gardens%20Hills%2FPomonok%2C33%2C14.27%2C16.65%2C26.17%2C21.41%2C54%0A11368%2CCorona%2FNorth%20Corona%2C101%2C30.47%2C16.13%2C22.4%2C21.51%2C-6%0A11369%2CAirport%2FEast%20Elmhurst%2C15%2C10.97%2C13.71%2C8.23%2C8.23%2C-33%0A11370%2CJackson%20Heights%2FRikers%20Island%2C30%2C12.21%2C24.42%2C42.74%2C12.21%2C50%0A11372%2CJackson%20Heights%2C68%2C25.57%2C22.38%2C38.36%2C22.38%2C27%0A11373%2CElmhurst%2C64%2C17.23%2C24.76%2C17.23%2C9.69%2C-36%0A11374%2CRego%20Park%2C44%2C30.92%2C26.16%2C19.03%2C28.54%2C-17%0A11375%2CForest%20Hills%2C85%2C28.35%2C29.76%2C29.76%2C32.6%2C7%0A11377%2CWoodside%2C38%2C13.88%2C12.72%2C10.41%2C6.94%2C-35%0A11378%2CMaspeth%2C22%2C14.45%2C20.24%2C11.56%2C17.34%2C-17%0A11379%2CMiddle%20Village%2C20%2C11.05%2C13.81%2C19.34%2C11.05%2C22%0A11385%2CGlendale%2FRidgewood%2C54%2C13.6%2C9.72%2C14.57%2C14.57%2C25%0A11411%2CCambria%20Heights%2C6%2C4.88%2C14.64%2C0%2C9.76%2C-50%0A11412%2CSt.%20Albans%2C15%2C15.25%2C10.17%2C10.17%2C2.54%2C-50%0A11413%2CLaurelton%2FRosedale%2C19%2C11.46%2C9.16%2C13.75%2C9.16%2C11%0A11414%2CHamilton%20Beach%2FHoward%20Beach%2FLindenwood%2C19%2C7.08%2C28.3%2C24.77%2C7.08%2C-10%0A11415%2CKew%20Gardens%2C15%2C5.2%2C15.6%2C26%2C31.19%2C175%0A11416%2COzone%20Park%2C24%2C22.54%2C18.79%2C26.3%2C22.54%2C18%0A11417%2COzone%20Park%2C24%2C22.39%2C31.98%2C15.99%2C6.4%2C-59%0A11418%2CRichmond%20Hill%2C20%2C18.37%2C5.25%2C15.75%2C13.12%2C22%0A11419%2CRichmond%20Hill%2FSouth%20Ozone%20Park%2C37%2C19.67%2C15.73%2C21.63%2C15.73%2C6%0A11420%2CSouth%20Ozone%20Park%2C42%2C10.33%2C22.72%2C35.11%2C18.59%2C63%0A11421%2CWoodhaven%2C33%2C26.06%2C16.58%2C16.58%2C18.95%2C-17%0A11422%2CRosedale%2C17%2C5.93%2C5.93%2C20.76%2C17.79%2C225%0A11423%2CHollis%2FHolliswood%2C27%2C18.73%2C18.73%2C18.73%2C28.09%2C25%0A11426%2CBellerose%2C8%2C4.91%2C9.82%2C14.73%2C9.82%2C67%0A11427%2CBellerose%2FHollis%20Hills%2FHolliswood%2C12%2C4.31%2C8.62%2C21.54%2C17.23%2C200%0A11428%2CQueens%20Village%2C12%2C15.52%2C15.52%2C15.52%2C15.52%2C0%0A11429%2CQueens%20Village%2C14%2C10.7%2C10.7%2C10.7%2C17.83%2C33%0A11432%2CHillcrest%2FJamaica%20Estates%2FJamaica%20Hills%2C74%2C26.9%2C41.14%2C28.48%2C20.57%2C-28%0A11433%2CJamaica%2C26%2C16.65%2C27.75%2C13.88%2C13.88%2C-38%0A11434%2CAirport%2FSouth%20Jamaica%2FSpringfield%20Gardens%2FSt.%20Albans%2C35%2C8.88%2C10.36%2C17.77%2C14.81%2C69%0A11435%2CBriarwood%2FJamaica%2C50%2C26.01%2C17.34%2C20.81%2C22.54%2C0%0A11436%2CSouth%20Jamaica%2FSouth%20Ozone%20Park%2C8%2C4.81%2C9.61%2C9.61%2C14.42%2C67%0A11691%2CEdgemere%2FFar%20Rockaway%2C103%2C27.8%2C30.88%2C37.06%2C63.31%2C71%0A11692%2CArverne%2FEdgemere%2C16%2C24.85%2C34.79%2C9.94%2C9.94%2C-67%0A11693%2CArverne%2FBroad%20Channel%2C2%2C0%2C8.08%2C0%2C8.08%2C0%0A11694%2CBelle%20Harbor-Neponsit%2FRockaway%20Park%2C19%2C24.56%2C19.65%2C34.39%2C14.74%2C11%0A11697%2CBreezy%20Point%2C4%2C56.55%2C0%2C28.28%2C28.28%2C0](url)

**Comment by MSamyal** [comment]
go to
1. https://www1.nyc.gov/site/doh/covid/covid-19-data-recent.page
2. Recent Case Data by ZIP Code
3. click on table
4. Left side, below table click on 'Get the Data'
you'll get CSV file
